### ISSUE TITLE
Re-subscription with different parameters doesn't update count

### ISSUE THREAD

**Issue by arkwood** [percolatestudio/publish-counts#38]
Hi, 

I have a filter object attached to my user, which determines the query to run against my collection. Additionally I have pagination support with a limit (load-more scenario):

My publication:

    Meteor.publish('filtercustomer', function(limit) {
        if(this.userId) {
            console.log('re-subscribing');
            var query = getCustomerFilter(this.userId);
            Counts.publish(this, 'total-engagements', customers.find(query.filter));
            return customers.find(query.filter, {
                sort: query.sort,
                limit: parseInt(limit)
            });
        }
    });

As I modify my filter object via the UI (by applying new filters or removing old filters) I re-subscribe to this publication (I see the text "re-subscribing" on the server console whenever I change the filter). In the UI I also see a different list of entries (according to the selected filters). 

The only thing that doesn't change is the "Total" at the bottom of my list, which is also used to determine if the "Show More" link is displayed. The helper showing the total uses `Count.get('total-engagements')`. 

I've tried using a `Session` variable as well, but for some reason the `Counts.publish` doesn't seem to update my counter, which I retrieve via `Counts.get`.

**Comment by arkwood** [comment]
Workaround: I need to run to the server and fetch the new count every time I update my filter and use a session variable in my template helper.

**Comment by tmeasday** [comment]
Hi @arkwood,

I'd be surprised if that publication re-ran just because you changed some fields on the user (publications aren't reactive in that way). But if you are seeing "re-subscribing" on the server, I guess it is?

Can you put together a simple reproduction in the style of https://github.com/meteor/meteor/wiki/Contributing-to-Meteor#reporting-a-bug-in-meteor please? That would make it a lot easier to figure this out.

**Comment by arkwood** [comment]
Hi Tom (@tmeasday),

I trigger the re-subscription explicitly. For a reproducible example, please clone: https://github.com/arkwood/tmeasday-publish-counts-refreshissue

**Steps to repeat:**

- Clone repository
- Start server and access the page (http://localhost:3000)
- You are already logged in and the filter is `{ a : 'b' }` - total entries: 1
- Click on the "Change to filter C" link

**Expected:**

- The list of entries updates to all 4 entries (which is correct, since I haven't stopped the initial subscription).
- The total should show 3 now since I update the `Count` when I trigger the re-subscription in the click event

**Problem**

- The total still shows 1. Either the `Count` is not reactive or the re-subscription doesn't properly update the `Count`.

**Comment by tmeasday** [comment]
Hi @arkwood,

Thanks very much for the reproduction, it makes it very clear.

The issue is that you aren't stopping the original subscription. You'll notice that the `b` record is still visible. As both subscriptions are running, it's not surprising that the choice of which subscription's count wins is fairly arbitrary.

The solution is to stop the original subscription. The way it's usually done is to put it in an autorun, something like:

```
Tracker.autorun(function() {
    // create a reactive dependency on the user, so this code re-runs whenever the user changes.
    Meteor.user();

    Meteor.subscribe('entriesPub');
});
```

This won't work however because of an optimization that the stack does where it won't re-subscribe to the same subscription with the same arguments. To get around this, the simplest solution is probably to just pass a random argument to the sub, so it's different everytime.

```
Tracker.autorun(function() {
    // create a reactive dependency on the user, so this code re-runs whenever the user changes.
    Meteor.user();

    Meteor.subscribe('entriesPub', Random.id());
});
```

If you wanted to be really clever you could hash the filter client side so it doesn't re-subscribe when other user properties change.

An alternate approach would be to use a publication join library to achieve this. This is a complicated topic though so I won't go into it here..
