### ISSUE TITLE
countFromField returning number of objects instead of sum of fields.

### ISSUE THREAD

**Issue by vacarsu** [percolatestudio/publish-counts#42]
Publish Method:
```javascript
Meteor.publish('student-points-earned', function (courseId) {
  Counts.publish(this, 'points-earned', AssignmentBox.find({ 'student._id': this.userId, 'status': 'graded', 'course': courseId }), { countFromField: 'pointsEarned' });
});
```

subscription:
```javascript
$scope.$meteorSubscribe('student-points-earned', this.courseId).then(() => {
  this.totalEarnedPoints = $scope.$meteorObject(Counts, 'points-earned', false);
  console.log(this.totalEarnedPoints);
})
```

**Comment by boxofrox** [comment]
Any particular reason you're not using `Counts.get('points-earned')`?

**Comment by vacarsu** [comment]
It's angular, I think if I use the normal collection.get angular won't be able to detect changes.

**Comment by boxofrox** [comment]
Ah.  I don't know angular.  What's the name of the meteor package providing angular in your case?  I suspect publish-counts isn't playing well with it.

**Comment by vacarsu** [comment]
It's called urigo:angular
https://atmospherejs.com/urigo/angular

**Comment by boxofrox** [comment]
Thanks, I'll dig around and see what I can find.

**Comment by boxofrox** [comment]
I don't suppose this alteration gets you the count you're looking for, otherwise you wouldn't be getting a record count instead...
```js
console.log(this.totalEarnedPoints.count);
```

Also of note, your subscription takes that `courseId` param, which implies to me you may be calling it multiple times, and doing so binds multiple subscriptions to Count's `'points-earned'` document.  Not sure if the last subscription overrides those before it, or they all fight to set the counter.  Anyway, you might consider augmenting the count name with the course id like so:

```js
Meteor.publish('student-points-earned', function (courseId) {
  Counts.publish(this, 'points-earned-' + courseId, AssignmentBox.find({ 'student._id': this.userId, 'status': 'graded', 'course': courseId }), { countFromField: 'pointsEarned' });
});
```

**Comment by vacarsu** [comment]
That logs the same object.

**Comment by boxofrox** [comment]
I didn't expect `.count` to reference the object stored in `this.totalEarnedPoints`.

The reason I brought it up is that publish-counts defines `Counts.get` in the browser as...

```js
  Counts.get = function(name) {
    var count = this.findOne(name);      // get mongodb document
    return count && count.count || 0;    // return value of count field or zero
  };
```
...and will return `count.count`; or `0` when the former is undefined.

Whereas, in urigo/angular `$scope.$meteorObject` is defined as...

```js
/* $meteorObject factory */
angularMeteorObject.factory('$meteorObject', ['$rootScope', '$meteorUtils', 'AngularMeteorObject',
  function($rootScope, $meteorUtils, AngularMeteorObject) {
    return function(collection, id, auto, options) {
      ...
      var data = new AngularMeteorObject(collection, id, options);
      ...
      return data;
    };
  }]);

/* $meteorObject constructor */
  var createAngularMeteorObject = function(collection, id, options){
    // Make data not be an object so we can extend it to preserve
    // Collection Helpers and the like
    var data = new function SubObject() {};
    var doc = collection.findOne(id, options)         // (1)
    angular.extend(data, doc);                        // (2)

    data._serverBackup = doc || {};
    data.$$collection = collection;
    data.$$options = options;
    data.$$id = id;

    angular.extend(data, AngularMeteorObject);        // (3)

    return data;
  };
```

(1) effectively matches the code in `Counts.get` for obtaining the mongodb document, but the similarities stop there.  (2) indicates that the field `doc.count` is copied into `data`, hence my suggestion to alter your `console.log`.  I'm not sure whether (3) overwrites `data.count`.  Given all the `$` prefixes I see in Angular, I would expect that convention to avoid any overwrite in this case.

So, where do we stand?  Without angular, the publish-counts library works for me; I updated the test suite for publish-counts to comprehensively test basic counts, countByField, and countByFieldLength; and the code for publish-counts is simple enough that it should be working as you expect.  This is to say, angular is the only variation in this case where publish-counts misbehaves, so I'm inclined to suspect angular is the source of this problem.

Do you have a sample app that demonstrates this behavior I could download?

Does your test case only subscribe once to `'student-points-earned'` or multiple times?

If multiple times, could you limit the app to one subscription and retest?

**Comment by vacarsu** [comment]
What I meant is when I log this.totalPointsEarned what is logged under the .count is the same as logging this.totalPointsEarned.count. Sorry for the confusion.

**Comment by boxofrox** [comment]
One more thing to check.  Does `this.totalEarnedPoints.count` match `this.totalEarnedPoints._serverBackup.count`?

**Comment by vacarsu** [comment]
_serverback.count returns the same number. I'm also having the same problem with countFromFieldLength. it returns the number of objects found from the cursor and not the sum of the field length or the count from total fields.

**Comment by boxofrox** [comment]
Well, at least the number is consistent between the backup and front-end value.  Four months later, I really can't recall if there was more to that train of thought.

At this point, I don't have enough information and the responses to my inquiries are difficult for me to decipher.  I haven't worked with Angular at all, so before I can assist further, I need a basic Angular app that demonstrates this problem.  I can poke and prod at that until I get it working and give you an answer.  Otherwise, you'll have to figure it out yourself or wait for someone more knowledgable than me to take over.

- Create an empty Angular app.
- Add a collection similar to `AssignmentBox` (only needs `status`, `pointsEarned`, `student._id`, and `course`).
- In your server startup code, populate `AssignmentBox` with test records.  Figure on 2 students, 1 course, 3-5 graded assignments per student, and at least 1 ungraded assignment per student.
- Publish your 'points-earned' count (server), subscribe to it (client), and log or render the count on the page (client).
- Test the app yourself, make sure it generates the wrong values.  Write down the exact value that was wrong, and the exact value you expected.  Put those values in the README.md.
- If there are any special steps to run the app beyond `meteor run`, please include in README.md a detailed procedure so I can repeat the same steps you did.
- Commit this project to a git repo, push to github, and drop a link to it here.

**Comment by vacarsu** [comment]
I created a simple reproduction. I didn't use the same object as AssignmentBox, as I'm getting the issue on an even simpler example. Check the repo here https://github.com/vacarsu/publish-counts-reproduction

Both publications are returning the same count, which is the number of documents.

**Comment by boxofrox** [comment]
Thank you very much for the example.  Here are the changes I made to produce the correct counts.

```diff
diff --git a/server/publications/counts.js b/server/publications/counts.js
index 95b827d..993d7b4 100644
--- a/server/publications/counts.js
+++ b/server/publications/counts.js
@@ -1,7 +1,9 @@
 Meteor.publish('post-likes-count', function() {
-  Counts.publish(this, 'total-likes', Posts.find({}, { countFromFieldLength: 'likes' }));
+  Counts.publish(this, 'total-likes', Posts.find({}), { countFromFieldLength: 'likes' });
 });

 Meteor.publish('post-like-count', function() {
-  Counts.publish(this, 'post-like', Posts.find({}, { countFromField: function(doc) { doc.likes.like } }));
+  Counts.publish(this, 'post-like', Posts.find({}, {fields: {_id: 1, likes: 1}}), { countFromField: function(doc) {
+    return doc.likes.reduce(function (sum, entry) {
+      return sum + entry.like;
+    }, 0);
+  }});
 });
```

In both counts, the `options` argument was given to the `Posts.find()` call instead of `Counts.publish()`.  Since `Counts.publish()` didn't see any options, it defaults to counting the number of docs, which is consistent with your symptoms.

In the second count, `'post-like'`, `doc.likes.like` is insufficient since `doc.likes` contains an array of objects, so I also switched that to a sum reducing function.  I also added the field specifier `{fields: {_id: 1, likes: 1}}` to `Posts.find()` to squelch the warning from publish-counts in the server console.

Hopefully that corrects the counts in your app.  If not, let's apply this patch to the repo and update the code to reproduce the errors you still see.

**Comment by vacarsu** [comment]
Yeah it's working now, wow I feel silly that is a hard typo to find. Thanks for your help.
