### ISSUE TITLE
TypeError: Object [object global] has no method 'added' 

### ISSUE THREAD

**Issue by lyquocnam** [percolatestudio/publish-counts#84]
dear author, i try publish count but have this error, i don't know what happen, please help !

my code:

```
  Meteor.publish('categories.list', (params) => {
    const selector = params ? params.selector : {};
    const options = params ? params.options : {};

    Counts.publish(this, 'categories.count', Categories.find(selector));

    return Categories.find(selector, options);
  });

```

Error:

```
Exception from sub categories.list id JQhqZyf2mJPFYabSg TypeError: Object [object global] has no method 'added'
I20160409-08:16:06.470(7)?     at Object.Counts.publish (packages\tmeasday_publish-counts.js:97:10)
I20160409-08:16:06.470(7)?     at Subscription._handler (server/publish/categories.js:11:12)
I20160409-08:16:06.470(7)?     at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1704:12)
I20160409-08:16:06.470(7)?     at Subscription._runHandler (packages/ddp-server/livedata_server.js:1026:17)
I20160409-08:16:06.470(7)?     at Session._startSubscription (packages/ddp-server/livedata_server.js:845:9)
I20160409-08:16:06.470(7)?     at Session.sub (packages/ddp-server/livedata_server.js:617:12)
I20160409-08:16:06.471(7)?     at packages/ddp-server/livedata_server.js:551:43
```

**Comment by boxofrox** [comment]
@lyquocnam you're using the ES6 arrow function `=>` which binds the `this` context when the function is defined, not when its called back.

Specifically, you've done this.
```javascript
const self = this;
Meteor.publish('categories.list', (params) => {
  assert(this === self);  //=> true
});
```
Whereas, if you used `function () {}` instead, you'd get...
```javascript
const self = this;
Meteor.publish('categories.list', function (params) {
  assert(this === self);  //=> false
});
```

`Meteor.publish` is trying to use the `this` context of your callback function to pass in an object that defines the `added` method, but the use of fat arrow overrides that.

**Comment by lyquocnam** [comment]
@boxofrox   i see the problem, thanks so much ! :+1:

**Comment by rajish** [comment]
👍 It would be good to add this to some 'known issues' section in README

**Comment by boxofrox** [comment]
@rajish 

I've given this some thought, and disagree.  The issue here is indirectly related to publish-counts at best.  It just happens to be the victim and isn't complicit in the error.  I'd rather not use the README of this project to document problems in other projects.

This problem stems from an inappropriate use of `Meteor.publish` with the ES6 arrow function, and is best documented on Meteor.com.

After another glance at the OP, I now recognize that publish-counts is featured exclusively in the stack trace.  It sounded the alarm that a crime occurred and became the prime suspect, which is why we're here.  I stand my decision, however.  I could document this as "If you give publish-counts garbage arguments, you'll get errors and undefined behavior", which is not subject to change should Meteor ever support the arrow operator, but this is a fundamental truth that needs not to be said.

As always, I'm not the alpha and omega here.  Someone with more seniority on the team may overrule my choice.

I'd rather throw an error if the subscription argument fails a validation check, so the resulting error says "Argument error.  Your subscription object is invalid.", rather than the generic error in the OP.
